source 'http://rubygems.org' --no-verify
gem 'rest_client', :source => 'https://rubygems.org'
# gem 'rspec', :source => 'https://rubygems.org'
# gem 'page-object', :source => 'https://rubygems.org'
# gem 'yml_reader', :source => 'https://rubygems.org'
# gem 'data_magic', :source => 'https://rubygems.org'
# gem 'require_all', :source => 'https://rubygems.org'
# gem 'json', :source => 'https://rubygems.org'
# gem 'json_spec', :source => 'https://rubygems.org'
# gem 'jsonpath', :source => 'https://rubygems.org'
# gem 'json-compare', :source => 'https://rubygems.org'